version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    nepomuk:
        build: ./Nepomuk
        ports:
            - "8081:8080"
        depends_on:
            - kafka
        volumes:
            - ./data:/data
    cepheus:
        build: ./Cepheus
        ports:
            - "8082:8080"
        depends_on:
            - kafka
    cassiopeia:
        build: ./Cassiopeia
        ports:
            - "8083:8080"
        depends_on:
            - kafka
    giles:
        build: ./Giles
        ports:
            - "8080:8080"
        volumes:
            - ./data:/data
        depends_on:
            - kafka
    digilib:
        build: ./Digilib
        volumes:
            - ./data:/data
