version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    mysql:
        image: mysql/mysql-server:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "sqlpassword"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./scripts/mysql:/docker-entrypoint-initdb.d
    nepomuk:
        build: ./Nepomuk
        ports:
            - "8081:8080"
        depends_on:
            - kafka
            - mysql
        volumes:
            - ./data:/data
    cepheus:
        build: ./Cepheus
        ports:
            - "8082:8080"
        depends_on:
            - kafka
    andromeda:
        build: ./Andromeda
        ports:
            - "8084:8080"
        depends_on:
            - kafka
    cassiopeia:
        build: ./Cassiopeia
        ports:
            - "8083:8080"
        depends_on:
            - kafka
    giles:
        build: ./Giles
        ports:
            - "8080:8080"
        volumes:
            - ./data:/data
        depends_on:
            - kafka
            - mysql
            - nepomuk
    september:
        build: ./September
        ports:
            - "8085:8080"
        depends_on:
            - kafka
            - zookeeper
            - mysql
        volumes:
            - ./data:/data
    digilib:
        build: ./Digilib
        volumes:
            - ./data:/data
